repos:
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: markdownlint
        name: check markdown
        exclude: ^content/search.md$|^content/archive.md$
        args:
          - -r
          - ~MD002,~MD013,~MD024,~MD026,~MD028,~MD034

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        name: check spelling
        args:
          - -L
          - fpr

