baseURL: 'https://blog.freddeliv.me/'
languageCode: 'en-us'
title: "Xartos blog"
theme: 'PaperMod'
paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Xartos blog"
  description: "Personal blog for me and my projects"
  keywords: [Blog, Electronics, Programming, PaperMod]

  # TODO: Fix
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true

    # TODO FIX
    favicon: "favicon.png"
    favicon16x16: "favicon-16x16.png"
    # favicon32x32: "<link / abs url>"
    apple_touch_icon: "apple-touch-icon.png"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /favicon.png
    iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: "Welcome to my blog"
    Content: |-
      This blog is mainly for myself to document my projects.
      But who knows maybe more people find their way here.


  socialIcons:
    - name: github
      url: "https://github.com/Xartos"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: posts
      name: posts
      url: /archive/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: search
      url: /search/
      weight: 20
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
